version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-hotel
    ports:
      - "8083:8083"
    restart: no
    depends_on:
      - db-hotel
    networks:
      - internet
      - hotelnet

  db-hotel:
    image: postgres:14-alpine
    container_name: db-hotel
    environment:
      POSTGRES_DB: hotel_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5436
    ports:
      - "5436:5436"
    volumes:
      - hotel_db:/var/lib/postgresql/data
    restart: no
    networks:
      - hotelnet

volumes:
  hotel_db:

networks:
  internet:
    name: internet
    driver: bridge
  hotelnet:
    name: hotelnet
    driver: bridge